### ISSUE TITLE
solução não válida

### ISSUE THREAD

**Issue by ErosMLima** [Pleiterson/desafios-bootcamps-dio#1]
solução não válida poderia nos ajudar a resolver? (Grupo DIO)

**Comment by Pleiterson** [comment]
qual solução que não está válida?

**Comment by elissonbonfim** [comment]
Olá, melhor amigo do pablo não funcionou pra mim.
Não está imprimindo o primeiro nome, no caso do primeiro teste é Abhay.

**Comment by Pleiterson** [comment]
de qual linguagem? todos estes eu fiz na época que realizei os bootcamps e rodaram normalmente na plataforma da dio

**Comment by elissonbonfim** [comment]
JAVA

**Comment by andrericardoborba** [comment]
A DIO corrigiu o bug do desafio melhor amigo do Pablo, agora vc não precisa tirar o "Abhay" na hora de imprimir a saida.

**Comment by Pleiterson** [comment]
As correções foram realizadas na plataforma da DIO
